id = "zrpc"
name = "Zrpc"
description = "Zrpc syntax highlighting"
version = "0.0.1"
schema_version = 1
authors = ["Akzestia"]
repository = "https://github.com/Akzestia/zed-zrpc"

[grammars.zrpc]
repository = "https://github.com/Akzestia/tree-sitter-zrpc"
rev = "329be564b9042afbdba3d3b1855a2476bbb1d616"
